/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import test.requests.persistence.db.tables.Addresses;
import test.requests.persistence.db.tables.ApplicationDocumentFields;
import test.requests.persistence.db.tables.ApplicationSections;
import test.requests.persistence.db.tables.Individuals;
import test.requests.persistence.db.tables.Organizations;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Applications extends SchemaImpl {

    private static final long serialVersionUID = 62204547;

    /**
     * The reference instance of <code>applications</code>
     */
    public static final Applications APPLICATIONS = new Applications();

    /**
     * Адреса заявителей
     */
    public final Addresses ADDRESSES = test.requests.persistence.db.tables.Addresses.ADDRESSES;

    /**
     * Поля документов заявления
     */
    public final ApplicationDocumentFields APPLICATION_DOCUMENT_FIELDS = test.requests.persistence.db.tables.ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS;

    /**
     * Секции заявлений
     */
    public final ApplicationSections APPLICATION_SECTIONS = test.requests.persistence.db.tables.ApplicationSections.APPLICATION_SECTIONS;

    /**
     * Заявления
     */
    public final test.requests.persistence.db.tables.Applications APPLICATIONS_ = test.requests.persistence.db.tables.Applications.APPLICATIONS_;

    /**
     * Заявители - физические лица
     */
    public final Individuals INDIVIDUALS = test.requests.persistence.db.tables.Individuals.INDIVIDUALS;

    /**
     * Заявители - юридические лица
     */
    public final Organizations ORGANIZATIONS = test.requests.persistence.db.tables.Organizations.ORGANIZATIONS;

    /**
     * No further instances allowed
     */
    private Applications() {
        super("applications", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ADDRESSES_ID_SEQ,
            Sequences.APPLICATION_DOCUMENT_FIELDS_ID_SEQ,
            Sequences.APPLICATION_SECTIONS_ID_SEQ,
            Sequences.APPLICATIONS_ID_SEQ,
            Sequences.INDIVIDUALS_ID_SEQ,
            Sequences.ORGANIZATIONS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Addresses.ADDRESSES,
            ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS,
            ApplicationSections.APPLICATION_SECTIONS,
            test.requests.persistence.db.tables.Applications.APPLICATIONS_,
            Individuals.INDIVIDUALS,
            Organizations.ORGANIZATIONS);
    }
}
