/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import test.requests.persistence.db.tables.Addresses;
import test.requests.persistence.db.tables.ApplicationDocumentFields;
import test.requests.persistence.db.tables.ApplicationSections;
import test.requests.persistence.db.tables.Applications;
import test.requests.persistence.db.tables.Individuals;
import test.requests.persistence.db.tables.Organizations;
import test.requests.persistence.db.tables.records.AddressesRecord;
import test.requests.persistence.db.tables.records.ApplicationDocumentFieldsRecord;
import test.requests.persistence.db.tables.records.ApplicationSectionsRecord;
import test.requests.persistence.db.tables.records.ApplicationsRecord;
import test.requests.persistence.db.tables.records.IndividualsRecord;
import test.requests.persistence.db.tables.records.OrganizationsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>applications</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AddressesRecord, Long> IDENTITY_ADDRESSES = Identities0.IDENTITY_ADDRESSES;
    public static final Identity<ApplicationDocumentFieldsRecord, Long> IDENTITY_APPLICATION_DOCUMENT_FIELDS = Identities0.IDENTITY_APPLICATION_DOCUMENT_FIELDS;
    public static final Identity<ApplicationSectionsRecord, Long> IDENTITY_APPLICATION_SECTIONS = Identities0.IDENTITY_APPLICATION_SECTIONS;
    public static final Identity<ApplicationsRecord, Long> IDENTITY_APPLICATIONS_ = Identities0.IDENTITY_APPLICATIONS_;
    public static final Identity<IndividualsRecord, Long> IDENTITY_INDIVIDUALS = Identities0.IDENTITY_INDIVIDUALS;
    public static final Identity<OrganizationsRecord, Long> IDENTITY_ORGANIZATIONS = Identities0.IDENTITY_ORGANIZATIONS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AddressesRecord> ADDRESSES_PKEY = UniqueKeys0.ADDRESSES_PKEY;
    public static final UniqueKey<ApplicationDocumentFieldsRecord> APPLICATION_DOCUMENT_FIELDS_PKEY = UniqueKeys0.APPLICATION_DOCUMENT_FIELDS_PKEY;
    public static final UniqueKey<ApplicationSectionsRecord> APPLICATION_SECTIONS_PKEY = UniqueKeys0.APPLICATION_SECTIONS_PKEY;
    public static final UniqueKey<ApplicationsRecord> APPLICATIONS_PKEY = UniqueKeys0.APPLICATIONS_PKEY;
    public static final UniqueKey<ApplicationsRecord> APPLICATIONS_NUMBER_KEY = UniqueKeys0.APPLICATIONS_NUMBER_KEY;
    public static final UniqueKey<IndividualsRecord> INDIVIDUALS_PKEY = UniqueKeys0.INDIVIDUALS_PKEY;
    public static final UniqueKey<OrganizationsRecord> ORGANIZATIONS_PKEY = UniqueKeys0.ORGANIZATIONS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ApplicationDocumentFieldsRecord, ApplicationSectionsRecord> APPLICATION_DOCUMENT_FIELDS__FK_SECTIONS_DOCUMENT_FIELDS = ForeignKeys0.APPLICATION_DOCUMENT_FIELDS__FK_SECTIONS_DOCUMENT_FIELDS;
    public static final ForeignKey<ApplicationSectionsRecord, ApplicationsRecord> APPLICATION_SECTIONS__FK_APPLICATIONS_SECTIONS = ForeignKeys0.APPLICATION_SECTIONS__FK_APPLICATIONS_SECTIONS;
    public static final ForeignKey<ApplicationsRecord, IndividualsRecord> APPLICATIONS__FK_APPLICATIONS_INDIVIDUALS = ForeignKeys0.APPLICATIONS__FK_APPLICATIONS_INDIVIDUALS;
    public static final ForeignKey<ApplicationsRecord, OrganizationsRecord> APPLICATIONS__FK_APPLICATIONS_ORGANIZATIONS = ForeignKeys0.APPLICATIONS__FK_APPLICATIONS_ORGANIZATIONS;
    public static final ForeignKey<IndividualsRecord, AddressesRecord> INDIVIDUALS__FK_APPLICANT_ADDRESS_LIVING = ForeignKeys0.INDIVIDUALS__FK_APPLICANT_ADDRESS_LIVING;
    public static final ForeignKey<IndividualsRecord, AddressesRecord> INDIVIDUALS__FK_APPLICANT_ADDRESS_REGISTRATION = ForeignKeys0.INDIVIDUALS__FK_APPLICANT_ADDRESS_REGISTRATION;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AddressesRecord, Long> IDENTITY_ADDRESSES = Internal.createIdentity(Addresses.ADDRESSES, Addresses.ADDRESSES.ID);
        public static Identity<ApplicationDocumentFieldsRecord, Long> IDENTITY_APPLICATION_DOCUMENT_FIELDS = Internal.createIdentity(ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS, ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS.ID);
        public static Identity<ApplicationSectionsRecord, Long> IDENTITY_APPLICATION_SECTIONS = Internal.createIdentity(ApplicationSections.APPLICATION_SECTIONS, ApplicationSections.APPLICATION_SECTIONS.ID);
        public static Identity<ApplicationsRecord, Long> IDENTITY_APPLICATIONS_ = Internal.createIdentity(Applications.APPLICATIONS_, Applications.APPLICATIONS_.ID);
        public static Identity<IndividualsRecord, Long> IDENTITY_INDIVIDUALS = Internal.createIdentity(Individuals.INDIVIDUALS, Individuals.INDIVIDUALS.ID);
        public static Identity<OrganizationsRecord, Long> IDENTITY_ORGANIZATIONS = Internal.createIdentity(Organizations.ORGANIZATIONS, Organizations.ORGANIZATIONS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AddressesRecord> ADDRESSES_PKEY = Internal.createUniqueKey(Addresses.ADDRESSES, "addresses_pkey", Addresses.ADDRESSES.ID);
        public static final UniqueKey<ApplicationDocumentFieldsRecord> APPLICATION_DOCUMENT_FIELDS_PKEY = Internal.createUniqueKey(ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS, "application_document_fields_pkey", ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS.ID);
        public static final UniqueKey<ApplicationSectionsRecord> APPLICATION_SECTIONS_PKEY = Internal.createUniqueKey(ApplicationSections.APPLICATION_SECTIONS, "application_sections_pkey", ApplicationSections.APPLICATION_SECTIONS.ID);
        public static final UniqueKey<ApplicationsRecord> APPLICATIONS_PKEY = Internal.createUniqueKey(Applications.APPLICATIONS_, "applications_pkey", Applications.APPLICATIONS_.ID);
        public static final UniqueKey<ApplicationsRecord> APPLICATIONS_NUMBER_KEY = Internal.createUniqueKey(Applications.APPLICATIONS_, "applications_number_key", Applications.APPLICATIONS_.NUMBER);
        public static final UniqueKey<IndividualsRecord> INDIVIDUALS_PKEY = Internal.createUniqueKey(Individuals.INDIVIDUALS, "individuals_pkey", Individuals.INDIVIDUALS.ID);
        public static final UniqueKey<OrganizationsRecord> ORGANIZATIONS_PKEY = Internal.createUniqueKey(Organizations.ORGANIZATIONS, "organizations_pkey", Organizations.ORGANIZATIONS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ApplicationDocumentFieldsRecord, ApplicationSectionsRecord> APPLICATION_DOCUMENT_FIELDS__FK_SECTIONS_DOCUMENT_FIELDS = Internal.createForeignKey(test.requests.persistence.db.Keys.APPLICATION_SECTIONS_PKEY, ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS, "application_document_fields__fk_sections_document_fields", ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS.SECTION_ID);
        public static final ForeignKey<ApplicationSectionsRecord, ApplicationsRecord> APPLICATION_SECTIONS__FK_APPLICATIONS_SECTIONS = Internal.createForeignKey(test.requests.persistence.db.Keys.APPLICATIONS_PKEY, ApplicationSections.APPLICATION_SECTIONS, "application_sections__fk_applications_sections", ApplicationSections.APPLICATION_SECTIONS.APPLICATION_ID);
        public static final ForeignKey<ApplicationsRecord, IndividualsRecord> APPLICATIONS__FK_APPLICATIONS_INDIVIDUALS = Internal.createForeignKey(test.requests.persistence.db.Keys.INDIVIDUALS_PKEY, Applications.APPLICATIONS_, "applications__fk_applications_individuals", Applications.APPLICATIONS_.APPLICANT_ID);
        public static final ForeignKey<ApplicationsRecord, OrganizationsRecord> APPLICATIONS__FK_APPLICATIONS_ORGANIZATIONS = Internal.createForeignKey(test.requests.persistence.db.Keys.ORGANIZATIONS_PKEY, Applications.APPLICATIONS_, "applications__fk_applications_organizations", Applications.APPLICATIONS_.APPLICANT_ID);
        public static final ForeignKey<IndividualsRecord, AddressesRecord> INDIVIDUALS__FK_APPLICANT_ADDRESS_LIVING = Internal.createForeignKey(test.requests.persistence.db.Keys.ADDRESSES_PKEY, Individuals.INDIVIDUALS, "individuals__fk_applicant_address_living", Individuals.INDIVIDUALS.LIVING_ADDRESS_ID);
        public static final ForeignKey<IndividualsRecord, AddressesRecord> INDIVIDUALS__FK_APPLICANT_ADDRESS_REGISTRATION = Internal.createForeignKey(test.requests.persistence.db.Keys.ADDRESSES_PKEY, Individuals.INDIVIDUALS, "individuals__fk_applicant_address_registration", Individuals.INDIVIDUALS.REGISTRATION_ADDRESS_ID);
    }
}
