/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in applications
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>applications.addresses_id_seq</code>
     */
    public static final Sequence<Long> ADDRESSES_ID_SEQ = new SequenceImpl<Long>("addresses_id_seq", Applications.APPLICATIONS, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>applications.application_document_fields_id_seq</code>
     */
    public static final Sequence<Long> APPLICATION_DOCUMENT_FIELDS_ID_SEQ = new SequenceImpl<Long>("application_document_fields_id_seq", Applications.APPLICATIONS, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>applications.application_sections_id_seq</code>
     */
    public static final Sequence<Long> APPLICATION_SECTIONS_ID_SEQ = new SequenceImpl<Long>("application_sections_id_seq", Applications.APPLICATIONS, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>applications.applications_id_seq</code>
     */
    public static final Sequence<Long> APPLICATIONS_ID_SEQ = new SequenceImpl<Long>("applications_id_seq", Applications.APPLICATIONS, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>applications.individuals_id_seq</code>
     */
    public static final Sequence<Long> INDIVIDUALS_ID_SEQ = new SequenceImpl<Long>("individuals_id_seq", Applications.APPLICATIONS, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>applications.organizations_id_seq</code>
     */
    public static final Sequence<Long> ORGANIZATIONS_ID_SEQ = new SequenceImpl<Long>("organizations_id_seq", Applications.APPLICATIONS, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
