/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db;


import javax.annotation.Generated;

import test.requests.persistence.db.tables.Addresses;
import test.requests.persistence.db.tables.ApplicationDocumentFields;
import test.requests.persistence.db.tables.ApplicationSections;
import test.requests.persistence.db.tables.Applications;
import test.requests.persistence.db.tables.Individuals;
import test.requests.persistence.db.tables.Organizations;


/**
 * Convenience access to all tables in applications
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Адреса заявителей
     */
    public static final Addresses ADDRESSES = test.requests.persistence.db.tables.Addresses.ADDRESSES;

    /**
     * Поля документов заявления
     */
    public static final ApplicationDocumentFields APPLICATION_DOCUMENT_FIELDS = test.requests.persistence.db.tables.ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS;

    /**
     * Секции заявлений
     */
    public static final ApplicationSections APPLICATION_SECTIONS = test.requests.persistence.db.tables.ApplicationSections.APPLICATION_SECTIONS;

    /**
     * Заявления
     */
    public static final Applications APPLICATIONS_ = test.requests.persistence.db.tables.Applications.APPLICATIONS_;

    /**
     * Заявители - физические лица
     */
    public static final Individuals INDIVIDUALS = test.requests.persistence.db.tables.Individuals.INDIVIDUALS;

    /**
     * Заявители - юридические лица
     */
    public static final Organizations ORGANIZATIONS = test.requests.persistence.db.tables.Organizations.ORGANIZATIONS;
}
