/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * Поля документов заявления
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationDocumentFields implements Serializable {

    private static final long serialVersionUID = -759625672;

    private Long   id;
    private Long   sectionId;
    private String name;
    private String description;
    private String fieldType;
    private String fieldOptions;
    private String value;

    public ApplicationDocumentFields() {}

    public ApplicationDocumentFields(ApplicationDocumentFields value) {
        this.id = value.id;
        this.sectionId = value.sectionId;
        this.name = value.name;
        this.description = value.description;
        this.fieldType = value.fieldType;
        this.fieldOptions = value.fieldOptions;
        this.value = value.value;
    }

    public ApplicationDocumentFields(
        Long   id,
        Long   sectionId,
        String name,
        String description,
        String fieldType,
        String fieldOptions,
        String value
    ) {
        this.id = id;
        this.sectionId = sectionId;
        this.name = name;
        this.description = description;
        this.fieldType = fieldType;
        this.fieldOptions = fieldOptions;
        this.value = value;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSectionId() {
        return this.sectionId;
    }

    public void setSectionId(Long sectionId) {
        this.sectionId = sectionId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getFieldType() {
        return this.fieldType;
    }

    public void setFieldType(String fieldType) {
        this.fieldType = fieldType;
    }

    public String getFieldOptions() {
        return this.fieldOptions;
    }

    public void setFieldOptions(String fieldOptions) {
        this.fieldOptions = fieldOptions;
    }

    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ApplicationDocumentFields (");

        sb.append(id);
        sb.append(", ").append(sectionId);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(fieldType);
        sb.append(", ").append(fieldOptions);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
