/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * Заявления
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Applications implements Serializable {

    private static final long serialVersionUID = -662178185;

    private Long      id;
    private String    number;
    private String    status;
    private Long      applicantId;
    private String    applicationType;
    private Timestamp created;
    private Timestamp changed;
    private String    creatorId;
    private String    updaterId;

    public Applications() {}

    public Applications(Applications value) {
        this.id = value.id;
        this.number = value.number;
        this.status = value.status;
        this.applicantId = value.applicantId;
        this.applicationType = value.applicationType;
        this.created = value.created;
        this.changed = value.changed;
        this.creatorId = value.creatorId;
        this.updaterId = value.updaterId;
    }

    public Applications(
        Long      id,
        String    number,
        String    status,
        Long      applicantId,
        String    applicationType,
        Timestamp created,
        Timestamp changed,
        String    creatorId,
        String    updaterId
    ) {
        this.id = id;
        this.number = number;
        this.status = status;
        this.applicantId = applicantId;
        this.applicationType = applicationType;
        this.created = created;
        this.changed = changed;
        this.creatorId = creatorId;
        this.updaterId = updaterId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNumber() {
        return this.number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getApplicantId() {
        return this.applicantId;
    }

    public void setApplicantId(Long applicantId) {
        this.applicantId = applicantId;
    }

    public String getApplicationType() {
        return this.applicationType;
    }

    public void setApplicationType(String applicationType) {
        this.applicationType = applicationType;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    public Timestamp getChanged() {
        return this.changed;
    }

    public void setChanged(Timestamp changed) {
        this.changed = changed;
    }

    public String getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId;
    }

    public String getUpdaterId() {
        return this.updaterId;
    }

    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Applications (");

        sb.append(id);
        sb.append(", ").append(number);
        sb.append(", ").append(status);
        sb.append(", ").append(applicantId);
        sb.append(", ").append(applicationType);
        sb.append(", ").append(created);
        sb.append(", ").append(changed);
        sb.append(", ").append(creatorId);
        sb.append(", ").append(updaterId);

        sb.append(")");
        return sb.toString();
    }
}
