/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * Заявители - физические лица
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Individuals implements Serializable {

    private static final long serialVersionUID = 1975433899;

    private Long    id;
    private String  identifier;
    private String  lastName;
    private String  firstName;
    private String  patronymic;
    private String  passportNo;
    private Date    regDate;
    private Long    livingAddressId;
    private Long    registrationAddressId;
    private String  passportSeries;
    private Date    passportIssueDate;
    private String  passportIssueAuthority;
    private Boolean active;

    public Individuals() {}

    public Individuals(Individuals value) {
        this.id = value.id;
        this.identifier = value.identifier;
        this.lastName = value.lastName;
        this.firstName = value.firstName;
        this.patronymic = value.patronymic;
        this.passportNo = value.passportNo;
        this.regDate = value.regDate;
        this.livingAddressId = value.livingAddressId;
        this.registrationAddressId = value.registrationAddressId;
        this.passportSeries = value.passportSeries;
        this.passportIssueDate = value.passportIssueDate;
        this.passportIssueAuthority = value.passportIssueAuthority;
        this.active = value.active;
    }

    public Individuals(
        Long    id,
        String  identifier,
        String  lastName,
        String  firstName,
        String  patronymic,
        String  passportNo,
        Date    regDate,
        Long    livingAddressId,
        Long    registrationAddressId,
        String  passportSeries,
        Date    passportIssueDate,
        String  passportIssueAuthority,
        Boolean active
    ) {
        this.id = id;
        this.identifier = identifier;
        this.lastName = lastName;
        this.firstName = firstName;
        this.patronymic = patronymic;
        this.passportNo = passportNo;
        this.regDate = regDate;
        this.livingAddressId = livingAddressId;
        this.registrationAddressId = registrationAddressId;
        this.passportSeries = passportSeries;
        this.passportIssueDate = passportIssueDate;
        this.passportIssueAuthority = passportIssueAuthority;
        this.active = active;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getPatronymic() {
        return this.patronymic;
    }

    public void setPatronymic(String patronymic) {
        this.patronymic = patronymic;
    }

    public String getPassportNo() {
        return this.passportNo;
    }

    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    public Date getRegDate() {
        return this.regDate;
    }

    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    public Long getLivingAddressId() {
        return this.livingAddressId;
    }

    public void setLivingAddressId(Long livingAddressId) {
        this.livingAddressId = livingAddressId;
    }

    public Long getRegistrationAddressId() {
        return this.registrationAddressId;
    }

    public void setRegistrationAddressId(Long registrationAddressId) {
        this.registrationAddressId = registrationAddressId;
    }

    public String getPassportSeries() {
        return this.passportSeries;
    }

    public void setPassportSeries(String passportSeries) {
        this.passportSeries = passportSeries;
    }

    public Date getPassportIssueDate() {
        return this.passportIssueDate;
    }

    public void setPassportIssueDate(Date passportIssueDate) {
        this.passportIssueDate = passportIssueDate;
    }

    public String getPassportIssueAuthority() {
        return this.passportIssueAuthority;
    }

    public void setPassportIssueAuthority(String passportIssueAuthority) {
        this.passportIssueAuthority = passportIssueAuthority;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Individuals (");

        sb.append(id);
        sb.append(", ").append(identifier);
        sb.append(", ").append(lastName);
        sb.append(", ").append(firstName);
        sb.append(", ").append(patronymic);
        sb.append(", ").append(passportNo);
        sb.append(", ").append(regDate);
        sb.append(", ").append(livingAddressId);
        sb.append(", ").append(registrationAddressId);
        sb.append(", ").append(passportSeries);
        sb.append(", ").append(passportIssueDate);
        sb.append(", ").append(passportIssueAuthority);
        sb.append(", ").append(active);

        sb.append(")");
        return sb.toString();
    }
}
