/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * Заявители - юридические лица
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizations implements Serializable {

    private static final long serialVersionUID = -1685752734;

    private Long   id;
    private String identifier;
    private String orgNameShort;
    private String orgNameFull;
    private String inn;
    private String ogrn;
    private Date   regDate;
    private Long   actualAddressId;
    private Long   legalAddressId;

    public Organizations() {}

    public Organizations(Organizations value) {
        this.id = value.id;
        this.identifier = value.identifier;
        this.orgNameShort = value.orgNameShort;
        this.orgNameFull = value.orgNameFull;
        this.inn = value.inn;
        this.ogrn = value.ogrn;
        this.regDate = value.regDate;
        this.actualAddressId = value.actualAddressId;
        this.legalAddressId = value.legalAddressId;
    }

    public Organizations(
        Long   id,
        String identifier,
        String orgNameShort,
        String orgNameFull,
        String inn,
        String ogrn,
        Date   regDate,
        Long   actualAddressId,
        Long   legalAddressId
    ) {
        this.id = id;
        this.identifier = identifier;
        this.orgNameShort = orgNameShort;
        this.orgNameFull = orgNameFull;
        this.inn = inn;
        this.ogrn = ogrn;
        this.regDate = regDate;
        this.actualAddressId = actualAddressId;
        this.legalAddressId = legalAddressId;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public String getOrgNameShort() {
        return this.orgNameShort;
    }

    public void setOrgNameShort(String orgNameShort) {
        this.orgNameShort = orgNameShort;
    }

    public String getOrgNameFull() {
        return this.orgNameFull;
    }

    public void setOrgNameFull(String orgNameFull) {
        this.orgNameFull = orgNameFull;
    }

    public String getInn() {
        return this.inn;
    }

    public void setInn(String inn) {
        this.inn = inn;
    }

    public String getOgrn() {
        return this.ogrn;
    }

    public void setOgrn(String ogrn) {
        this.ogrn = ogrn;
    }

    public Date getRegDate() {
        return this.regDate;
    }

    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    public Long getActualAddressId() {
        return this.actualAddressId;
    }

    public void setActualAddressId(Long actualAddressId) {
        this.actualAddressId = actualAddressId;
    }

    public Long getLegalAddressId() {
        return this.legalAddressId;
    }

    public void setLegalAddressId(Long legalAddressId) {
        this.legalAddressId = legalAddressId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organizations (");

        sb.append(id);
        sb.append(", ").append(identifier);
        sb.append(", ").append(orgNameShort);
        sb.append(", ").append(orgNameFull);
        sb.append(", ").append(inn);
        sb.append(", ").append(ogrn);
        sb.append(", ").append(regDate);
        sb.append(", ").append(actualAddressId);
        sb.append(", ").append(legalAddressId);

        sb.append(")");
        return sb.toString();
    }
}
