/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import test.requests.persistence.db.tables.ApplicationDocumentFields;


/**
 * Поля документов заявления
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationDocumentFieldsRecord extends UpdatableRecordImpl<ApplicationDocumentFieldsRecord> implements Record7<Long, Long, String, String, String, String, String> {

    private static final long serialVersionUID = 266947428;

    /**
     * Setter for <code>applications.application_document_fields.id</code>. ID поля документов
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>applications.application_document_fields.id</code>. ID поля документов
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>applications.application_document_fields.section_id</code>. ID секции заявления
     */
    public void setSectionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>applications.application_document_fields.section_id</code>. ID секции заявления
     */
    public Long getSectionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>applications.application_document_fields.name</code>. Название поля документа
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>applications.application_document_fields.name</code>. Название поля документа
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>applications.application_document_fields.description</code>. Описание поля документа
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>applications.application_document_fields.description</code>. Описание поля документа
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>applications.application_document_fields.field_type</code>. Тип поля документа
     */
    public void setFieldType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>applications.application_document_fields.field_type</code>. Тип поля документа
     */
    public String getFieldType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>applications.application_document_fields.field_options</code>. Возможные значения полей документа
     */
    public void setFieldOptions(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>applications.application_document_fields.field_options</code>. Возможные значения полей документа
     */
    public String getFieldOptions() {
        return (String) get(5);
    }

    /**
     * Setter for <code>applications.application_document_fields.value</code>. Значение поля документа
     */
    public void setValue(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>applications.application_document_fields.value</code>. Значение поля документа
     */
    public String getValue() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS.SECTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS.FIELD_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS.FIELD_OPTIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getSectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFieldType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFieldOptions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getSectionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFieldType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFieldOptions();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDocumentFieldsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDocumentFieldsRecord value2(Long value) {
        setSectionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDocumentFieldsRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDocumentFieldsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDocumentFieldsRecord value5(String value) {
        setFieldType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDocumentFieldsRecord value6(String value) {
        setFieldOptions(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDocumentFieldsRecord value7(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationDocumentFieldsRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicationDocumentFieldsRecord
     */
    public ApplicationDocumentFieldsRecord() {
        super(ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS);
    }

    /**
     * Create a detached, initialised ApplicationDocumentFieldsRecord
     */
    public ApplicationDocumentFieldsRecord(Long id, Long sectionId, String name, String description, String fieldType, String fieldOptions, String value) {
        super(ApplicationDocumentFields.APPLICATION_DOCUMENT_FIELDS);

        set(0, id);
        set(1, sectionId);
        set(2, name);
        set(3, description);
        set(4, fieldType);
        set(5, fieldOptions);
        set(6, value);
    }
}
