/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import test.requests.persistence.db.tables.ApplicationSections;


/**
 * Секции заявлений
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApplicationSectionsRecord extends UpdatableRecordImpl<ApplicationSectionsRecord> implements Record7<Long, Long, String, String, String, String, Long> {

    private static final long serialVersionUID = 1833600684;

    /**
     * Setter for <code>applications.application_sections.id</code>. ID секции заявления
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>applications.application_sections.id</code>. ID секции заявления
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>applications.application_sections.application_id</code>. ID заявления
     */
    public void setApplicationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>applications.application_sections.application_id</code>. ID заявления
     */
    public Long getApplicationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>applications.application_sections.name</code>. Название секции
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>applications.application_sections.name</code>. Название секции
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>applications.application_sections.description</code>. Описание секции
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>applications.application_sections.description</code>. Описание секции
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>applications.application_sections.document_code</code>. Код документа
     */
    public void setDocumentCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>applications.application_sections.document_code</code>. Код документа
     */
    public String getDocumentCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>applications.application_sections.document_designation</code>. Назначение документа
     */
    public void setDocumentDesignation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>applications.application_sections.document_designation</code>. Назначение документа
     */
    public String getDocumentDesignation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>applications.application_sections.document_id</code>. ID документа, связанного с секцией
     */
    public void setDocumentId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>applications.application_sections.document_id</code>. ID документа, связанного с секцией
     */
    public Long getDocumentId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, String, String, String, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Long, String, String, String, String, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ApplicationSections.APPLICATION_SECTIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ApplicationSections.APPLICATION_SECTIONS.APPLICATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ApplicationSections.APPLICATION_SECTIONS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ApplicationSections.APPLICATION_SECTIONS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ApplicationSections.APPLICATION_SECTIONS.DOCUMENT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ApplicationSections.APPLICATION_SECTIONS.DOCUMENT_DESIGNATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return ApplicationSections.APPLICATION_SECTIONS.DOCUMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDocumentCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDocumentDesignation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getDocumentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getApplicationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDocumentCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDocumentDesignation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getDocumentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationSectionsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationSectionsRecord value2(Long value) {
        setApplicationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationSectionsRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationSectionsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationSectionsRecord value5(String value) {
        setDocumentCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationSectionsRecord value6(String value) {
        setDocumentDesignation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationSectionsRecord value7(Long value) {
        setDocumentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ApplicationSectionsRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ApplicationSectionsRecord
     */
    public ApplicationSectionsRecord() {
        super(ApplicationSections.APPLICATION_SECTIONS);
    }

    /**
     * Create a detached, initialised ApplicationSectionsRecord
     */
    public ApplicationSectionsRecord(Long id, Long applicationId, String name, String description, String documentCode, String documentDesignation, Long documentId) {
        super(ApplicationSections.APPLICATION_SECTIONS);

        set(0, id);
        set(1, applicationId);
        set(2, name);
        set(3, description);
        set(4, documentCode);
        set(5, documentDesignation);
        set(6, documentId);
    }
}
