/*
 * This file is generated by jOOQ.
 */
package test.requests.persistence.db.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import test.requests.persistence.db.tables.Organizations;


/**
 * Заявители - юридические лица
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationsRecord extends UpdatableRecordImpl<OrganizationsRecord> implements Record9<Long, String, String, String, String, String, Date, Long, Long> {

    private static final long serialVersionUID = -584196232;

    /**
     * Setter for <code>applications.organizations.id</code>. ID заявителя
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>applications.organizations.id</code>. ID заявителя
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>applications.organizations.identifier</code>. Идентификатор заявителя
     */
    public void setIdentifier(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>applications.organizations.identifier</code>. Идентификатор заявителя
     */
    public String getIdentifier() {
        return (String) get(1);
    }

    /**
     * Setter for <code>applications.organizations.org_name_short</code>. Краткое наименование заявителя
     */
    public void setOrgNameShort(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>applications.organizations.org_name_short</code>. Краткое наименование заявителя
     */
    public String getOrgNameShort() {
        return (String) get(2);
    }

    /**
     * Setter for <code>applications.organizations.org_name_full</code>. Полное наименование заявителя
     */
    public void setOrgNameFull(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>applications.organizations.org_name_full</code>. Полное наименование заявителя
     */
    public String getOrgNameFull() {
        return (String) get(3);
    }

    /**
     * Setter for <code>applications.organizations.inn</code>. ИНН заявителя
     */
    public void setInn(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>applications.organizations.inn</code>. ИНН заявителя
     */
    public String getInn() {
        return (String) get(4);
    }

    /**
     * Setter for <code>applications.organizations.ogrn</code>. ОГРН заявителя
     */
    public void setOgrn(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>applications.organizations.ogrn</code>. ОГРН заявителя
     */
    public String getOgrn() {
        return (String) get(5);
    }

    /**
     * Setter for <code>applications.organizations.reg_date</code>. Дата регистрации заявителя
     */
    public void setRegDate(Date value) {
        set(6, value);
    }

    /**
     * Getter for <code>applications.organizations.reg_date</code>. Дата регистрации заявителя
     */
    public Date getRegDate() {
        return (Date) get(6);
    }

    /**
     * Setter for <code>applications.organizations.actual_address_id</code>. ID фактического адреса
     */
    public void setActualAddressId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>applications.organizations.actual_address_id</code>. ID фактического адреса
     */
    public Long getActualAddressId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>applications.organizations.legal_address_id</code>. ID юридического адреса
     */
    public void setLegalAddressId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>applications.organizations.legal_address_id</code>. ID юридического адреса
     */
    public Long getLegalAddressId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, String, Date, Long, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, String, Date, Long, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Organizations.ORGANIZATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Organizations.ORGANIZATIONS.IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Organizations.ORGANIZATIONS.ORG_NAME_SHORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Organizations.ORGANIZATIONS.ORG_NAME_FULL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Organizations.ORGANIZATIONS.INN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Organizations.ORGANIZATIONS.OGRN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field7() {
        return Organizations.ORGANIZATIONS.REG_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Organizations.ORGANIZATIONS.ACTUAL_ADDRESS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Organizations.ORGANIZATIONS.LEGAL_ADDRESS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrgNameShort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getOrgNameFull();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getInn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getOgrn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component7() {
        return getRegDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getActualAddressId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getLegalAddressId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrgNameShort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getOrgNameFull();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getOgrn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value7() {
        return getRegDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getActualAddressId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getLegalAddressId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value2(String value) {
        setIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value3(String value) {
        setOrgNameShort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value4(String value) {
        setOrgNameFull(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value5(String value) {
        setInn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value6(String value) {
        setOgrn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value7(Date value) {
        setRegDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value8(Long value) {
        setActualAddressId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value9(Long value) {
        setLegalAddressId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Date value7, Long value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationsRecord
     */
    public OrganizationsRecord() {
        super(Organizations.ORGANIZATIONS);
    }

    /**
     * Create a detached, initialised OrganizationsRecord
     */
    public OrganizationsRecord(Long id, String identifier, String orgNameShort, String orgNameFull, String inn, String ogrn, Date regDate, Long actualAddressId, Long legalAddressId) {
        super(Organizations.ORGANIZATIONS);

        set(0, id);
        set(1, identifier);
        set(2, orgNameShort);
        set(3, orgNameFull);
        set(4, inn);
        set(5, ogrn);
        set(6, regDate);
        set(7, actualAddressId);
        set(8, legalAddressId);
    }
}
